import sys
global mensagem
global chave
global opção

chave = ""
mensagem = ""
opção = ""

dicionario_pt = ["a","A","b","B","c","C","d","D","e","E","f","F","g","G","h","H","i","I","j","J","k","K","l","L","m","M","n","N","o","O","p","P","q","Q","r","R","s","S","t","T","u","U","v","V","w","W","x","X","y","Y","z","Z","Ç","ç","?","!",",",".",":"," ","1","2","3","4","5","6","7","8","9","0"]
matriz =[
    ['qY2DK', 'nK8xj', 'Z60kQ', 'DRqvb', 'PWDPZ', 'ZGD74', 'GKINj', 'GY3RN', 'DOAnc', 'KH7vd', 'sMlfG', 'PLu7Z', 'xgXl7', 'CTnjV', 'qGkVx', 'SKKMb', 'dfyJw', 'gwDDb', '7Rhe9', '1wwGD', 'FAJxR', '8T4GG', 'p7qpy', 'dOprv', 'o7LoJ', 'ON3rg', 'bcmMy', 'GqvJI', 'WCx5Z', 's0wsh', '97tWK', 'fFJEm', 'dGPhd', 'yTbM9', 'HKAJy', 'fXyg5', 'rjdd0', 'Dzwnf', 'xwo7N', 'uvLzv', '8mjL1', 'XrNZ7', 'LDplC', 'ftHiZ', 'Sbp92', 'UjCHg', 'Awq5q', 'iewSm', 'ZDVCd', 'uZQ7V', 'dk60w', 'zvWbW', '3SOuu', 'Bx7mF', 'que8g', 'YrwUg', '13btZ', 'JvKbv', 'ZhnMj', 'b14eW', 'kTDfx', 'TxRwT', 'eAfrD', 'pi82R', 'FTRmz', 'yfxio', 'YIgvr', 'Gvkhc', 'nMdF0', 'CECMF'],
    ['ZDVCd', 'p7qpy', 'CTnjV', 'XrNZ7', '7Rhe9', 'Gvkhc', '8mjL1', 'PWDPZ', 'zvWbW', 'fXyg5', 'HKAJy', 'o7LoJ', 'ZhnMj', 'yfxio', 'FAJxR', 'gwDDb', 'YIgvr', 'dGPhd', 'fFJEm', 'iewSm', 'ZGD74', 'pi82R', 'PLu7Z', '8T4GG', 'eAfrD', 'UjCHg', 'qGkVx', 'GY3RN', 'Z60kQ', '13btZ', 'GqvJI', 'Dzwnf', 'xwo7N', 'dfyJw', 'rjdd0', 'nMdF0', 'qY2DK', 'DRqvb', 's0wsh', 'bcmMy', 'FTRmz', '3SOuu', 'sMlfG', 'WCx5Z', '97tWK', 'JvKbv', 'Sbp92', 'b14eW', 'TxRwT', 'uZQ7V', 'yTbM9', 'uvLzv', 'DOAnc', 'LDplC', 'KH7vd', 'GKINj', 'ON3rg', 'dOprv', '1wwGD', 'dk60w', 'ftHiZ', 'YrwUg', 'que8g', 'Awq5q', 'CECMF', 'nK8xj', 'SKKMb', 'kTDfx', 'xgXl7', 'Bx7mF'],
    ['CECMF', 'bcmMy', 'TxRwT', 'CTnjV', 'pi82R', 'JvKbv', 'FAJxR', 'PLu7Z', 'fFJEm', 'xgXl7', 'nMdF0', 'Dzwnf', '97tWK', 'b14eW', 'Bx7mF', 'Gvkhc', 'WCx5Z', 'Sbp92', 'GY3RN', 'que8g', 'GqvJI', 'ON3rg', '7Rhe9', 'sMlfG', 'ftHiZ', '13btZ', 'DOAnc', 'ZhnMj', 'dOprv', 'rjdd0', 'GKINj', 's0wsh', 'fXyg5', 'xwo7N', '8mjL1', 'kTDfx', 'yfxio', '3SOuu', 'qY2DK', 'zvWbW', 'ZDVCd', 'FTRmz', 'p7qpy', 'yTbM9', '1wwGD', 'Awq5q', 'qGkVx', 'SKKMb', 'KH7vd', 'o7LoJ', 'YIgvr', 'iewSm', 'uvLzv', 'eAfrD', 'XrNZ7', 'dGPhd', 'nK8xj', 'YrwUg', 'dfyJw', 'PWDPZ', '8T4GG', 'LDplC', 'UjCHg', 'Z60kQ', 'dk60w', 'DRqvb', 'uZQ7V', 'HKAJy', 'ZGD74', 'gwDDb'],
    ['qY2DK', '8mjL1', 'b14eW', 'DOAnc', 'ZGD74', 'nK8xj', 'XrNZ7', 'bcmMy', 'kTDfx', 'uZQ7V', 'Dzwnf', 'ON3rg', '7Rhe9', 'dk60w', 'zvWbW', 's0wsh', 'nMdF0', 'SKKMb', 'CECMF', '13btZ', 'fFJEm', 'o7LoJ', 'Z60kQ', 'qGkVx', 'ZhnMj', 'uvLzv', 'CTnjV', 'Bx7mF', 'PWDPZ', 'KH7vd', 'PLu7Z', 'GY3RN', 'FTRmz', 'eAfrD', 'ZDVCd', '97tWK', 'FAJxR', 'gwDDb', '3SOuu', '1wwGD', 'rjdd0', 'p7qpy', 'dfyJw', 'que8g', 'JvKbv', '8T4GG', 'HKAJy', 'WCx5Z', 'UjCHg', 'Sbp92', 'yTbM9', 'xwo7N', 'dOprv', 'TxRwT', 'DRqvb', 'iewSm', 'yfxio', 'Gvkhc', 'sMlfG', 'LDplC', 'YIgvr', 'fXyg5', 'Awq5q', 'pi82R', 'YrwUg', 'GKINj', 'ftHiZ', 'GqvJI', 'dGPhd', 'xgXl7'],
    ['Z60kQ', 'GKINj', 'qY2DK', 'nK8xj', 'que8g', 'JvKbv', 'dOprv', 'ZhnMj', 'ftHiZ', 'UjCHg', 'DOAnc', 'Awq5q', '8mjL1', 'Sbp92', 'FTRmz', 'yTbM9', 'zvWbW', 'dk60w', 'dGPhd', 'eAfrD', 'PWDPZ', 'iewSm', 'ON3rg', 'HKAJy', 'LDplC', 'fFJEm', 'p7qpy', 'WCx5Z', 'xgXl7', 'bcmMy', '97tWK', 'sMlfG', 'CECMF', 'b14eW', 'CTnjV', 'nMdF0', 'fXyg5', 'TxRwT', 'Gvkhc', '1wwGD', 'Bx7mF', '13btZ', 'YrwUg', 's0wsh', 'xwo7N', 'kTDfx', 'uZQ7V', 'Dzwnf', 'ZGD74', 'GY3RN', 'FAJxR', '3SOuu', 'qGkVx', 'pi82R', 'yfxio', 'ZDVCd', 'KH7vd', 'PLu7Z', 'o7LoJ', 'YIgvr', 'DRqvb', 'rjdd0', '7Rhe9', '8T4GG', 'XrNZ7', 'gwDDb', 'GqvJI', 'SKKMb', 'dfyJw', 'uvLzv'],
    ['sMlfG', 'iewSm', 'dk60w', 'ON3rg', 'rjdd0', 'UjCHg', '3SOuu', 'kTDfx', 'yfxio', 'eAfrD', 'FTRmz', 'GY3RN', 'PWDPZ', 'DOAnc', 'qGkVx', 'bcmMy', 'WCx5Z', 'KH7vd', 'GKINj', 'o7LoJ', 'xwo7N', 'nMdF0', 'JvKbv', 'YIgvr', 'Awq5q', 'ZGD74', 'Dzwnf', 'ftHiZ', '7Rhe9', 'Bx7mF', 'b14eW', 'PLu7Z', 'fXyg5', 'p7qpy', 'SKKMb', 'ZDVCd', 'CECMF', 'pi82R', 'XrNZ7', 'Gvkhc', 'qY2DK', 'ZhnMj', 'FAJxR', 'gwDDb', 'Sbp92', '8T4GG', 'que8g', 'Z60kQ', 'HKAJy', 'fFJEm', '13btZ', 'dfyJw', 'xgXl7', 'yTbM9', 'LDplC', '1wwGD', 'YrwUg', 'dOprv', 'nK8xj', 'zvWbW', '97tWK', 'DRqvb', 'GqvJI', 'TxRwT', 'dGPhd', 'uvLzv', 'uZQ7V', 's0wsh', '8mjL1', 'CTnjV'],
    ['Gvkhc', 'nK8xj', 'UjCHg', '8mjL1', 'xwo7N', 'WCx5Z', 'GqvJI', 'yfxio', 'fXyg5', 'FAJxR', 'nMdF0', 'zvWbW', 'SKKMb', '1wwGD', 'p7qpy', '97tWK', 'Z60kQ', 'ZDVCd', 'PWDPZ', 'pi82R', 'YrwUg', 'yTbM9', 'DOAnc', 'sMlfG', 'CECMF', 'GKINj', 'Awq5q', 'rjdd0', 'kTDfx', 'uvLzv', 'KH7vd', 'DRqvb', 'o7LoJ', '7Rhe9', 'qY2DK', 'CTnjV', 'JvKbv', 'qGkVx', 'FTRmz', 'YIgvr', 'LDplC', 'dfyJw', 'Sbp92', 'dGPhd', 'uZQ7V', 'gwDDb', 'eAfrD', 'xgXl7', 'iewSm', 'Dzwnf', 'bcmMy', 'fFJEm', 'b14eW', 'ON3rg', 'PLu7Z', 'TxRwT', 'GY3RN', 'Bx7mF', '13btZ', 'XrNZ7', '3SOuu', 'dk60w', 'HKAJy', 'ZGD74', 'ZhnMj', 'ftHiZ', 's0wsh', 'que8g', 'dOprv', '8T4GG'],
    ['yTbM9', '8T4GG', 'UjCHg', 'GqvJI', '1wwGD', 'ON3rg', 'b14eW', 'PLu7Z', 'dk60w', '7Rhe9', 'dOprv', 'KH7vd', '8mjL1', 'rjdd0', 'HKAJy', 'GY3RN', 'Awq5q', 'gwDDb', 'ZGD74', 'kTDfx', 'YIgvr', 'fXyg5', 'uZQ7V', 'bcmMy', 'que8g', 'CECMF', 'yfxio', 'xgXl7', '97tWK', 'fFJEm', 'JvKbv', 'DOAnc', 'GKINj', 'eAfrD', 'p7qpy', 'uvLzv', '3SOuu', 'CTnjV', 'ZhnMj', 'ftHiZ', 'dGPhd', 'Sbp92', 'sMlfG', '13btZ', 'dfyJw', 'YrwUg', 'WCx5Z', 'xwo7N', 'o7LoJ', 'zvWbW', 'Gvkhc', 'nK8xj', 'SKKMb', 'XrNZ7', 'Dzwnf', 'qY2DK', 'ZDVCd', 'FAJxR', 'iewSm', 'qGkVx', 'DRqvb', 'LDplC', 'FTRmz', 'PWDPZ', 'nMdF0', 'Bx7mF', 'Z60kQ', 'pi82R', 'TxRwT', 's0wsh'],
    ['GqvJI', 'Gvkhc', 'fXyg5', '3SOuu', 'eAfrD', 's0wsh', 'ZhnMj', 'dOprv', 'dfyJw', '13btZ', 'UjCHg', 'KH7vd', 'DRqvb', 'qGkVx', 'DOAnc', 'nK8xj', '8mjL1', 'JvKbv', 'CECMF', 'PWDPZ', 'Dzwnf', 'b14eW', 'xgXl7', '7Rhe9', 'uvLzv', 'Bx7mF', 'yfxio', 'fFJEm', 'Sbp92', 'SKKMb', 'GKINj', 'dk60w', 'nMdF0', 'Z60kQ', '1wwGD', 'zvWbW', 'xwo7N', 'FTRmz', 'gwDDb', 'rjdd0', 'FAJxR', 'pi82R', 'ON3rg', 'o7LoJ', 'yTbM9', 'dGPhd', 'HKAJy', 'CTnjV', 'que8g', '97tWK', 'uZQ7V', 'YrwUg', '8T4GG', 'ftHiZ', 'iewSm', 'YIgvr', 'qY2DK', 'kTDfx', 'WCx5Z', 'bcmMy', 'GY3RN', 'p7qpy', 'sMlfG', 'TxRwT', 'ZDVCd', 'XrNZ7', 'ZGD74', 'Awq5q', 'PLu7Z', 'LDplC'],
    ['b14eW', 'ZDVCd', '7Rhe9', '8mjL1', 'dk60w', 'xwo7N', 'GY3RN', 'GKINj', 'YrwUg', 'eAfrD', '3SOuu', 'zvWbW', 'xgXl7', '1wwGD', 'Sbp92', '97tWK', 'iewSm', 'PWDPZ', 'fXyg5', 'PLu7Z', 'Gvkhc', 'UjCHg', '8T4GG', 'qY2DK', 'qGkVx', 'CECMF', 'fFJEm', 'WCx5Z', 'ZGD74', 'kTDfx', '13btZ', 'o7LoJ', 'KH7vd', 'Z60kQ', 's0wsh', 'ZhnMj', 'gwDDb', 'pi82R', 'DOAnc', 'DRqvb', 'Awq5q', 'dfyJw', 'FTRmz', 'uvLzv', 'uZQ7V', 'rjdd0', 'ON3rg', 'Bx7mF', 'HKAJy', 'FAJxR', 'p7qpy', 'sMlfG', 'nK8xj', 'YIgvr', 'yTbM9', 'que8g', 'dOprv', 'CTnjV', 'JvKbv', 'Dzwnf', 'bcmMy', 'yfxio', 'ftHiZ', 'SKKMb', 'XrNZ7', 'dGPhd', 'TxRwT', 'nMdF0', 'LDplC', 'GqvJI'],
    ['8T4GG', 'pi82R', 'CTnjV', 'xwo7N', 'dOprv', 'Awq5q', '3SOuu', 'Z60kQ', '7Rhe9', 'PWDPZ', 'CECMF', 's0wsh', 'GqvJI', 'ZDVCd', 'UjCHg', 'Sbp92', 'fXyg5', 'ZhnMj', '13btZ', 'WCx5Z', 'ftHiZ', 'bcmMy', 'JvKbv', 'dGPhd', 'qGkVx', 'ON3rg', 'iewSm', 'FAJxR', 'LDplC', 'zvWbW', 'ZGD74', 'TxRwT', 'que8g', 'yTbM9', 'kTDfx', 'yfxio', 'uvLzv', 'KH7vd', 'FTRmz', 'SKKMb', 'DOAnc', 'HKAJy', 'XrNZ7', 'DRqvb', 'uZQ7V', 'rjdd0', 'gwDDb', 'o7LoJ', '1wwGD', 'qY2DK', 'p7qpy', 'dfyJw', 'b14eW', 'fFJEm', 'sMlfG', 'dk60w', 'nMdF0', 'Dzwnf', 'YrwUg', '8mjL1', 'GY3RN', 'xgXl7', 'nK8xj', 'YIgvr', 'Bx7mF', 'PLu7Z', '97tWK', 'GKINj', 'Gvkhc', 'eAfrD'],
    ['gwDDb', 'zvWbW', 'qY2DK', 'qGkVx', 'ZhnMj', 'YIgvr', 'Z60kQ', 'YrwUg', 'sMlfG', '8mjL1', 'HKAJy', '13btZ', 'xwo7N', 'dfyJw', '3SOuu', 'WCx5Z', 'fXyg5', 'PLu7Z', 'Gvkhc', 'ftHiZ', 'Dzwnf', 'GqvJI', 'dOprv', 'TxRwT', 'DOAnc', 'bcmMy', 'Sbp92', 'kTDfx', 'GKINj', 'o7LoJ', 'UjCHg', 'Awq5q', 'dGPhd', 'LDplC', '1wwGD', 'KH7vd', 'nK8xj', 'ZDVCd', 'yTbM9', 'CECMF', 'que8g', '8T4GG', 'ZGD74', 'yfxio', 'DRqvb', 'dk60w', '97tWK', 'CTnjV', 'nMdF0', 'fFJEm', 'Bx7mF', 'XrNZ7', 'JvKbv', 'FAJxR', 'uvLzv', 'xgXl7', 'FTRmz', 'PWDPZ', 'eAfrD', '7Rhe9', 's0wsh', 'GY3RN', 'b14eW', 'SKKMb', 'ON3rg', 'p7qpy', 'rjdd0', 'uZQ7V', 'iewSm', 'pi82R'],
    ['yTbM9', 'gwDDb', 'UjCHg', 'xgXl7', 'CTnjV', 'ZDVCd', 'YrwUg', '97tWK', 's0wsh', 'FTRmz', 'nK8xj', 'PWDPZ', 'pi82R', 'uZQ7V', '13btZ', 'CECMF', 'ftHiZ', 'uvLzv', 'Bx7mF', 'Z60kQ', 'zvWbW', 'sMlfG', 'DOAnc', 'dGPhd', 'fFJEm', 'LDplC', 'qY2DK', 'FAJxR', 'Sbp92', 'Gvkhc', 'fXyg5', 'eAfrD', 'TxRwT', 'KH7vd', 'kTDfx', 'nMdF0', '1wwGD', 'b14eW', 'o7LoJ', 'WCx5Z', 'dOprv', 'que8g', 'DRqvb', 'Dzwnf', '8T4GG', 'YIgvr', '3SOuu', '7Rhe9', 'Awq5q', 'ZGD74', 'ZhnMj', 'GKINj', 'SKKMb', 'HKAJy', 'GY3RN', 'ON3rg', 'dk60w', 'GqvJI', '8mjL1', 'XrNZ7', 'rjdd0', 'PLu7Z', 'iewSm', 'JvKbv', 'p7qpy', 'dfyJw', 'qGkVx', 'bcmMy', 'yfxio', 'xwo7N'],
    ['qY2DK', 'xwo7N', 'qGkVx', 'fXyg5', 'SKKMb', 'Dzwnf', 'ZhnMj', 'yfxio', '8T4GG', 'pi82R', 'TxRwT', 'GY3RN', 'ZDVCd', 'YIgvr', 'LDplC', '13btZ', 'b14eW', 'dGPhd', 'dfyJw', 'dk60w', 'WCx5Z', 'GqvJI', 'uZQ7V', 'CECMF', 'gwDDb', 'p7qpy', 'KH7vd', 'Gvkhc', 'GKINj', 'kTDfx', '8mjL1', 'xgXl7', 'FAJxR', '97tWK', 'CTnjV', 'sMlfG', 'nK8xj', 'uvLzv', 'ftHiZ', 'bcmMy', 'DOAnc', 'fFJEm', 'Sbp92', 'que8g', 'PLu7Z', 'FTRmz', 'XrNZ7', 'ON3rg', '1wwGD', 'JvKbv', 'Bx7mF', 'Awq5q', 'dOprv', 'HKAJy', 'eAfrD', 'UjCHg', 'ZGD74', 'Z60kQ', '7Rhe9', 'YrwUg', 'PWDPZ', 'rjdd0', 'o7LoJ', 's0wsh', '3SOuu', 'zvWbW', 'iewSm', 'nMdF0', 'yTbM9', 'DRqvb'],
    ['Dzwnf', 'PWDPZ', 'sMlfG', 'uZQ7V', 'b14eW', 'HKAJy', 's0wsh', 'iewSm', '3SOuu', 'GqvJI', '7Rhe9', 'LDplC', '97tWK', 'KH7vd', 'rjdd0', 'nMdF0', 'Z60kQ', 'YrwUg', 'XrNZ7', 'UjCHg', 'xgXl7', 'bcmMy', 'FTRmz', 'yTbM9', 'ON3rg', 'zvWbW', '1wwGD', 'DOAnc', 'fFJEm', 'Sbp92', 'CTnjV', 'gwDDb', 'dOprv', 'o7LoJ', 'TxRwT', 'eAfrD', 'qGkVx', 'JvKbv', 'qY2DK', 'dk60w', 'Awq5q', '8mjL1', '13btZ', 'CECMF', 'yfxio', '8T4GG', 'ZGD74', 'kTDfx', 'DRqvb', 'fXyg5', 'uvLzv', 'dGPhd', 'que8g', 'ftHiZ', 'Bx7mF', 'Gvkhc', 'xwo7N', 'ZhnMj', 'p7qpy', 'PLu7Z', 'GKINj', 'SKKMb', 'YIgvr', 'nK8xj', 'FAJxR', 'pi82R', 'GY3RN', 'dfyJw', 'WCx5Z', 'ZDVCd'],
    ['ZDVCd', 'Z60kQ', 'nK8xj', 'o7LoJ', '13btZ', 'LDplC', 'UjCHg', '8mjL1', 'iewSm', 'GY3RN', 'YIgvr', 'pi82R', 'YrwUg', 'uvLzv', 'XrNZ7', 'ftHiZ', 'SKKMb', 'dk60w', 'CECMF', 'DRqvb', 'yTbM9', 'fFJEm', '8T4GG', 'sMlfG', 'dOprv', 'Bx7mF', '1wwGD', 'gwDDb', 'PWDPZ', 'xwo7N', 'Dzwnf', 'kTDfx', 'GqvJI', 'fXyg5', 'Sbp92', 'dGPhd', 'que8g', 'bcmMy', 'FAJxR', 'ZhnMj', 'TxRwT', 'b14eW', 'yfxio', 'FTRmz', 'eAfrD', 'xgXl7', 'zvWbW', 'p7qpy', 'JvKbv', 's0wsh', 'ON3rg', '3SOuu', 'nMdF0', 'uZQ7V', 'KH7vd', 'ZGD74', 'DOAnc', 'PLu7Z', 'qY2DK', '7Rhe9', '97tWK', 'Awq5q', 'WCx5Z', 'qGkVx', 'dfyJw', 'GKINj', 'HKAJy', 'CTnjV', 'rjdd0', 'Gvkhc'],
    ['CTnjV', 'KH7vd', 'p7qpy', 'kTDfx', 'xwo7N', 'SKKMb', 'pi82R', '8T4GG', 'GKINj', 'uZQ7V', '97tWK', 'ZDVCd', 'o7LoJ', 'DRqvb', 'Sbp92', 'ZGD74', 'dGPhd', 'fXyg5', 'FTRmz', 'sMlfG', 'YIgvr', 'UjCHg', 'dk60w', 'bcmMy', 'fFJEm', 'PLu7Z', 'HKAJy', 'nK8xj', 'rjdd0', 'iewSm', 'b14eW', 'yTbM9', 'que8g', 'xgXl7', 'CECMF', 'JvKbv', 'nMdF0', 'DOAnc', 'ZhnMj', 'Z60kQ', 'Bx7mF', 'yfxio', 'GqvJI', 'WCx5Z', 'gwDDb', 'zvWbW', 'LDplC', '13btZ', 'uvLzv', 's0wsh', 'dOprv', 'GY3RN', 'Gvkhc', '1wwGD', 'Awq5q', 'dfyJw', 'eAfrD', 'qY2DK', '3SOuu', '8mjL1', 'XrNZ7', 'TxRwT', '7Rhe9', 'YrwUg', 'ON3rg', 'PWDPZ', 'Dzwnf', 'qGkVx', 'FAJxR', 'ftHiZ'],
    ['dGPhd', 'ZGD74', 'rjdd0', 's0wsh', 'PWDPZ', 'pi82R', '3SOuu', 'GY3RN', 'GqvJI', 'nMdF0', 'o7LoJ', 'FTRmz', 'iewSm', 'KH7vd', 'bcmMy', 'zvWbW', 'kTDfx', 'dfyJw', 'gwDDb', '7Rhe9', 'Dzwnf', 'CECMF', 'DRqvb', 'DOAnc', 'XrNZ7', 'eAfrD', 'UjCHg', 'p7qpy', 'Z60kQ', '8mjL1', 'YIgvr', 'fFJEm', 'JvKbv', 'qGkVx', 'sMlfG', 'xgXl7', 'FAJxR', '97tWK', 'fXyg5', 'GKINj', 'nK8xj', 'ZDVCd', 'ZhnMj', 'TxRwT', 'dk60w', '1wwGD', 'uvLzv', 'CTnjV', 'Bx7mF', 'yTbM9', 'que8g', 'dOprv', 'PLu7Z', 'xwo7N', 'SKKMb', 'WCx5Z', '13btZ', 'Gvkhc', 'Awq5q', 'LDplC', 'ftHiZ', 'ON3rg', 'Sbp92', 'HKAJy', '8T4GG', 'uZQ7V', 'qY2DK', 'b14eW', 'YrwUg', 'yfxio'],
    ['ZGD74', 'uZQ7V', '13btZ', 'JvKbv', 'que8g', '97tWK', 'GqvJI', 'XrNZ7', 'dk60w', 'SKKMb', 'gwDDb', 'FAJxR', 'iewSm', 'o7LoJ', '3SOuu', 'rjdd0', 'ftHiZ', 'pi82R', 'ZDVCd', 's0wsh', 'xgXl7', 'TxRwT', 'ON3rg', 'DRqvb', 'b14eW', 'p7qpy', 'nK8xj', 'qY2DK', 'nMdF0', 'zvWbW', 'PWDPZ', 'YrwUg', 'sMlfG', 'GKINj', 'Awq5q', 'dOprv', 'Z60kQ', '1wwGD', 'yTbM9', 'YIgvr', 'KH7vd', 'GY3RN', 'fFJEm', 'UjCHg', 'Dzwnf', 'HKAJy', 'kTDfx', 'uvLzv', 'CTnjV', 'Gvkhc', 'DOAnc', 'ZhnMj', '8mjL1', '8T4GG', '7Rhe9', 'dfyJw', 'bcmMy', 'eAfrD', 'xwo7N', 'FTRmz', 'fXyg5', 'Bx7mF', 'dGPhd', 'qGkVx', 'LDplC', 'PLu7Z', 'CECMF', 'yfxio', 'Sbp92', 'WCx5Z'],
    ['xwo7N', '7Rhe9', 'rjdd0', 'dGPhd', 'YIgvr', 'DRqvb', 'Bx7mF', 'UjCHg', 'dfyJw', 'kTDfx', 'eAfrD', 'qY2DK', 'ZDVCd', 'YrwUg', 'p7qpy', 'nMdF0', 'FTRmz', 'CTnjV', 'bcmMy', 'pi82R', 'nK8xj', 'ZGD74', 'SKKMb', 'JvKbv', 'ZhnMj', 'o7LoJ', 'PWDPZ', 'dOprv', 'ftHiZ', 'fFJEm', 'FAJxR', 'Awq5q', 'XrNZ7', '1wwGD', 'b14eW', 'fXyg5', 'ON3rg', '3SOuu', 'HKAJy', 'qGkVx', 'Dzwnf', 'Z60kQ', 'gwDDb', 'Sbp92', 'uvLzv', '13btZ', '97tWK', 'KH7vd', 'yfxio', 'CECMF', 'GY3RN', 'TxRwT', 'dk60w', 'WCx5Z', 'DOAnc', 'xgXl7', 'GKINj', 'GqvJI', 'LDplC', '8T4GG', 'PLu7Z', 's0wsh', 'zvWbW', '8mjL1', 'yTbM9', 'sMlfG', 'uZQ7V', 'Gvkhc', 'que8g', 'iewSm'],
    ['dfyJw', 'nMdF0', 'rjdd0', 'DOAnc', 'JvKbv', 'GqvJI', 'ON3rg', 'ZGD74', 'pi82R', '1wwGD', 'Awq5q', 'qGkVx', 'yTbM9', 'HKAJy', 'GKINj', 'nK8xj', 'sMlfG', 'Sbp92', 'YrwUg', 'fFJEm', 'b14eW', 'dGPhd', 'GY3RN', '97tWK', '8mjL1', 'dOprv', 'uZQ7V', '7Rhe9', 'xgXl7', 'PWDPZ', 'eAfrD', 'ZhnMj', 'iewSm', 'xwo7N', 'CECMF', 'XrNZ7', 'kTDfx', 'dk60w', 'WCx5Z', 'SKKMb', '8T4GG', 'zvWbW', 'PLu7Z', 'LDplC', 'FTRmz', 'bcmMy', 'fXyg5', 'Z60kQ', 's0wsh', 'qY2DK', 'que8g', 'Gvkhc', 'YIgvr', '13btZ', 'ZDVCd', 'uvLzv', 'DRqvb', 'UjCHg', 'CTnjV', 'Bx7mF', 'FAJxR', 'Dzwnf', 'p7qpy', 'KH7vd', 'ftHiZ', 'yfxio', '3SOuu', 'gwDDb', 'o7LoJ', 'TxRwT'],
    ['7Rhe9', 'KH7vd', 'Awq5q', 'ON3rg', 'GY3RN', 'gwDDb', 'HKAJy', 's0wsh', 'xwo7N', 'GqvJI', 'ZGD74', 'qY2DK', '3SOuu', 'ZDVCd', 'qGkVx', 'DOAnc', 'que8g', '97tWK', 'TxRwT', 'dk60w', 'iewSm', 'JvKbv', 'fFJEm', 'PWDPZ', 'eAfrD', 'zvWbW', 'WCx5Z', 'b14eW', 'Gvkhc', 'CTnjV', 'YrwUg', 'LDplC', 'dfyJw', 'Bx7mF', 'rjdd0', 'pi82R', 'nMdF0', 'XrNZ7', 'o7LoJ', 'yfxio', 'FAJxR', 'Dzwnf', 'uvLzv', 'ZhnMj', 'PLu7Z', 'Sbp92', 'CECMF', 'fXyg5', 'GKINj', 'xgXl7', 'nK8xj', 'YIgvr', '8T4GG', 'DRqvb', '8mjL1', '13btZ', 'Z60kQ', 'dOprv', '1wwGD', 'dGPhd', 'kTDfx', 'FTRmz', 'bcmMy', 'p7qpy', 'ftHiZ', 'UjCHg', 'yTbM9', 'SKKMb', 'sMlfG', 'uZQ7V'],
    ['Gvkhc', 'dk60w', '97tWK', 'UjCHg', 'dOprv', 'fFJEm', 'ZhnMj', 'Awq5q', 'SKKMb', 'yfxio', 'WCx5Z', 'XrNZ7', 'PWDPZ', 'zvWbW', 'YIgvr', 'Dzwnf', 'DRqvb', 'o7LoJ', 'uvLzv', 'yTbM9', '13btZ', 'xgXl7', 'ON3rg', '1wwGD', '3SOuu', 'FAJxR', 'FTRmz', 'CECMF', 'p7qpy', 'dfyJw', 'DOAnc', 'que8g', 'nK8xj', '8mjL1', 'qGkVx', 'LDplC', 'ZGD74', 'fXyg5', 'KH7vd', 'Sbp92', '8T4GG', 'YrwUg', 'HKAJy', 'ZDVCd', 'TxRwT', 'GqvJI', 'qY2DK', 'xwo7N', 'b14eW', 'gwDDb', 'GY3RN', 'uZQ7V', 'Bx7mF', 's0wsh', 'PLu7Z', 'bcmMy', 'pi82R', 'Z60kQ', 'ftHiZ', 'eAfrD', 'CTnjV', 'iewSm', 'rjdd0', 'kTDfx', 'JvKbv', 'GKINj', 'nMdF0', 'sMlfG', '7Rhe9', 'dGPhd'],
    ['eAfrD', 'yfxio', '8mjL1', 'dfyJw', 'KH7vd', 'YIgvr', '97tWK', 'yTbM9', 'xwo7N', 'uvLzv', 'UjCHg', 'kTDfx', 'HKAJy', 'JvKbv', 'rjdd0', 'xgXl7', 'gwDDb', 'fXyg5', 'SKKMb', 'Bx7mF', 'XrNZ7', 'qGkVx', 'b14eW', 'dGPhd', 'ZGD74', 'CECMF', 'Awq5q', 'Z60kQ', 'DRqvb', '3SOuu', 'ftHiZ', 'Sbp92', 'fFJEm', 'Dzwnf', 'GY3RN', 'zvWbW', 'nMdF0', 'ON3rg', 'CTnjV', 'p7qpy', 'Gvkhc', 'iewSm', 'uZQ7V', 'YrwUg', 'WCx5Z', 'PLu7Z', '7Rhe9', 'LDplC', '1wwGD', 'bcmMy', 'FAJxR', 'ZDVCd', 'FTRmz', 'PWDPZ', 'DOAnc', 'qY2DK', 'TxRwT', 'GqvJI', 'ZhnMj', 'GKINj', 'sMlfG', 'o7LoJ', 'nK8xj', 'pi82R', '8T4GG', 'que8g', 'dOprv', 's0wsh', '13btZ', 'dk60w'],
    ['yTbM9', 'zvWbW', 'XrNZ7', 'pi82R', 'SKKMb', 'xwo7N', '3SOuu', 'que8g', 'KH7vd', 'PWDPZ', 'o7LoJ', 'qGkVx', 'UjCHg', 'Bx7mF', 'FTRmz', 'nK8xj', 'PLu7Z', 'kTDfx', 'ZGD74', 'uvLzv', 's0wsh', 'sMlfG', 'nMdF0', 'ZDVCd', 'gwDDb', 'ZhnMj', 'JvKbv', 'fFJEm', 'DOAnc', 'Dzwnf', '97tWK', 'dGPhd', 'bcmMy', 'GKINj', 'GY3RN', 'FAJxR', 'Sbp92', 'YIgvr', '13btZ', 'ftHiZ', 'TxRwT', '1wwGD', 'Gvkhc', 'rjdd0', 'Awq5q', 'dk60w', 'CTnjV', 'qY2DK', 'DRqvb', 'WCx5Z', 'YrwUg', 'eAfrD', 'LDplC', 'GqvJI', 'b14eW', '8T4GG', '7Rhe9', 'dfyJw', 'yfxio', 'Z60kQ', 'dOprv', '8mjL1', 'ON3rg', 'HKAJy', 'p7qpy', 'iewSm', 'fXyg5', 'CECMF', 'xgXl7', 'uZQ7V'],
    ['KH7vd', '8mjL1', 'DOAnc', 'eAfrD', 'nK8xj', 'que8g', 'YIgvr', 'qY2DK', 'dOprv', 'dk60w', 'kTDfx', 'ON3rg', '97tWK', 'SKKMb', 'GKINj', 'UjCHg', 'b14eW', '13btZ', 'Dzwnf', 'HKAJy', 'pi82R', 'CTnjV', '3SOuu', 'dfyJw', 'LDplC', 'o7LoJ', 'iewSm', '7Rhe9', '1wwGD', 'Z60kQ', 'xwo7N', 'PLu7Z', 'qGkVx', 'ftHiZ', 'bcmMy', 'uvLzv', 'JvKbv', 'FAJxR', '8T4GG', 'YrwUg', 'yfxio', 'Bx7mF', 'DRqvb', 'uZQ7V', 'Sbp92', 'CECMF', 'Awq5q', 'nMdF0', 'gwDDb', 'fFJEm', 'fXyg5', 'WCx5Z', 'TxRwT', 'dGPhd', 'zvWbW', 'PWDPZ', 'xgXl7', 'p7qpy', 's0wsh', 'ZhnMj', 'ZGD74', 'GY3RN', 'sMlfG', 'XrNZ7', 'FTRmz', 'Gvkhc', 'GqvJI', 'rjdd0', 'ZDVCd', 'yTbM9'],
    ['pi82R', 'uvLzv', 'dk60w', 'DRqvb', 'kTDfx', 'Gvkhc', 'eAfrD', 'FAJxR', 'uZQ7V', 'p7qpy', 'CTnjV', 'qGkVx', 'LDplC', '13btZ', 'TxRwT', 'bcmMy', 'GqvJI', 'ftHiZ', 'YrwUg', 'gwDDb', 'zvWbW', 'dGPhd', 'iewSm', 'KH7vd', 'fXyg5', 'o7LoJ', 'que8g', 'ZhnMj', 'JvKbv', 'yfxio', 'XrNZ7', '7Rhe9', 'Z60kQ', 'PLu7Z', 'b14eW', 'CECMF', 'SKKMb', '97tWK', 'YIgvr', '3SOuu', 'qY2DK', 'xwo7N', 'ZGD74', 'xgXl7', 'nMdF0', 'PWDPZ', 'Dzwnf', 'Bx7mF', 'rjdd0', 'HKAJy', 'UjCHg', '8T4GG', 'dOprv', 'nK8xj', 'FTRmz', 'Sbp92', 'GY3RN', '8mjL1', 'sMlfG', 'dfyJw', 'ON3rg', 'GKINj', '1wwGD', 'fFJEm', 'Awq5q', 'WCx5Z', 'DOAnc', 'ZDVCd', 'yTbM9', 's0wsh'],
    ['qGkVx', 'ZGD74', 'DRqvb', 'kTDfx', '13btZ', 'dk60w', 'ON3rg', 'nK8xj', 'FTRmz', 'dGPhd', 'PLu7Z', 'YrwUg', 'dfyJw', 'YIgvr', 'rjdd0', 'Gvkhc', 'Z60kQ', 'JvKbv', 'yTbM9', 'dOprv', 'Awq5q', 'TxRwT', 'ZhnMj', 'o7LoJ', 'LDplC', 'nMdF0', 'sMlfG', 'p7qpy', 'CECMF', 'pi82R', 'que8g', '3SOuu', 'fFJEm', 'GqvJI', 'xwo7N', 'yfxio', 'UjCHg', '8T4GG', 'WCx5Z', 'uvLzv', 'Bx7mF', 'KH7vd', 'PWDPZ', 'FAJxR', 'fXyg5', 'HKAJy', 'gwDDb', 'qY2DK', 'DOAnc', 'bcmMy', 'b14eW', 'GY3RN', 'uZQ7V', 'ZDVCd', 'CTnjV', 'Dzwnf', '1wwGD', '7Rhe9', 'SKKMb', 'iewSm', 'GKINj', 'Sbp92', 'zvWbW', 'eAfrD', 'ftHiZ', '8mjL1', 'XrNZ7', '97tWK', 's0wsh', 'xgXl7'],
    ['uZQ7V', '8T4GG', 'TxRwT', 'KH7vd', 'SKKMb', 'Dzwnf', 'dfyJw', 'xwo7N', 'ZDVCd', 'Awq5q', 'FAJxR', 'CECMF', 'o7LoJ', 'pi82R', 'Z60kQ', 'GKINj', 'GqvJI', 'Sbp92', 'fXyg5', 'dGPhd', 'PLu7Z', 'eAfrD', '1wwGD', 'WCx5Z', 'Gvkhc', 'ZGD74', 'nMdF0', 'qGkVx', 'xgXl7', 'DOAnc', 'yfxio', 'qY2DK', 'YrwUg', 'JvKbv', 'fFJEm', 'DRqvb', '97tWK', 'GY3RN', 'uvLzv', 'kTDfx', 'HKAJy', '3SOuu', 'CTnjV', 'iewSm', 'b14eW', 'que8g', 'PWDPZ', 'ON3rg', '7Rhe9', 'p7qpy', 'rjdd0', 'UjCHg', '8mjL1', 'bcmMy', 'zvWbW', 'LDplC', 'Bx7mF', 'ZhnMj', 'XrNZ7', 's0wsh', '13btZ', 'ftHiZ', 'YIgvr', 'yTbM9', 'nK8xj', 'dOprv', 'sMlfG', 'gwDDb', 'dk60w', 'FTRmz'],
    ['UjCHg', 'rjdd0', 'JvKbv', 'Bx7mF', 'GKINj', 'ON3rg', 'nMdF0', 'sMlfG', 'SKKMb', 'WCx5Z', 'ZhnMj', 'qGkVx', '97tWK', 'LDplC', 'YIgvr', 'ZDVCd', 'Gvkhc', 'KH7vd', '8T4GG', 'qY2DK', 'nK8xj', 'dfyJw', 'CECMF', 'Sbp92', 'p7qpy', 'XrNZ7', 'CTnjV', '13btZ', 'uZQ7V', 'o7LoJ', 'TxRwT', 'dGPhd', 's0wsh', 'ftHiZ', 'FAJxR', '7Rhe9', 'fFJEm', 'ZGD74', 'PLu7Z', 'b14eW', 'PWDPZ', 'xgXl7', 'YrwUg', 'GqvJI', 'GY3RN', 'DRqvb', 'uvLzv', 'Dzwnf', 'yTbM9', 'bcmMy', 'fXyg5', 'eAfrD', 'HKAJy', 'que8g', 'dk60w', 'Z60kQ', 'FTRmz', 'Awq5q', 'pi82R', 'zvWbW', 'DOAnc', 'dOprv', '8mjL1', 'gwDDb', 'yfxio', 'xwo7N', '1wwGD', 'kTDfx', 'iewSm', '3SOuu'],
    ['GY3RN', 'YrwUg', 'uZQ7V', 'ON3rg', 'DRqvb', 'TxRwT', 'ftHiZ', 'KH7vd', 'Sbp92', 's0wsh', 'Dzwnf', '8T4GG', 'xwo7N', 'Awq5q', '1wwGD', 'qY2DK', 'eAfrD', '13btZ', 'o7LoJ', 'YIgvr', 'kTDfx', 'CECMF', 'FAJxR', 'Bx7mF', 'qGkVx', 'ZhnMj', 'Gvkhc', 'b14eW', 'ZDVCd', 'uvLzv', 'gwDDb', 'nMdF0', 'LDplC', 'GqvJI', 'p7qpy', 'pi82R', 'yTbM9', 'iewSm', 'sMlfG', 'dOprv', 'UjCHg', 'HKAJy', 'CTnjV', '97tWK', 'dGPhd', '8mjL1', 'DOAnc', '3SOuu', 'WCx5Z', 'xgXl7', 'bcmMy', 'dfyJw', 'que8g', 'PWDPZ', 'SKKMb', 'GKINj', 'XrNZ7', 'rjdd0', 'JvKbv', 'FTRmz', 'Z60kQ', 'fFJEm', 'PLu7Z', '7Rhe9', 'fXyg5', 'zvWbW', 'nK8xj', 'dk60w', 'yfxio', 'ZGD74'],
    ['DOAnc', 'pi82R', 'b14eW', 'xwo7N', '8T4GG', 'eAfrD', 'LDplC', 'FTRmz', 'iewSm', 'fFJEm', 'yTbM9', 'ftHiZ', 'XrNZ7', 'nMdF0', 'Z60kQ', 'ZGD74', 'CECMF', 'HKAJy', 'SKKMb', 'uZQ7V', 'qY2DK', 'ZhnMj', 'GY3RN', 'PLu7Z', 'fXyg5', 'p7qpy', 'dk60w', 'sMlfG', 'Dzwnf', 'UjCHg', 'CTnjV', 'PWDPZ', 'Awq5q', 's0wsh', 'dOprv', 'uvLzv', 'ZDVCd', '3SOuu', 'rjdd0', 'bcmMy', 'GqvJI', 'que8g', 'yfxio', 'o7LoJ', '8mjL1', '1wwGD', '7Rhe9', 'Sbp92', 'KH7vd', 'zvWbW', 'WCx5Z', 'dGPhd', 'FAJxR', 'GKINj', 'Bx7mF', 'xgXl7', 'nK8xj', 'JvKbv', 'DRqvb', '13btZ', 'gwDDb', 'YrwUg', 'Gvkhc', '97tWK', 'qGkVx', 'TxRwT', 'kTDfx', 'ON3rg', 'YIgvr', 'dfyJw'],
    ['sMlfG', 'yTbM9', 'dk60w', 'que8g', 'YrwUg', 'TxRwT', '7Rhe9', 's0wsh', 'PLu7Z', 'kTDfx', 'dOprv', '3SOuu', 'Gvkhc', 'CTnjV', 'nMdF0', 'gwDDb', 'xgXl7', 'ON3rg', 'KH7vd', '1wwGD', 'LDplC', 'XrNZ7', 'Awq5q', 'DOAnc', 'Dzwnf', 'JvKbv', '97tWK', 'HKAJy', 'fFJEm', 'p7qpy', 'ZDVCd', 'xwo7N', 'nK8xj', '13btZ', 'YIgvr', 'GKINj', 'GqvJI', 'SKKMb', 'rjdd0', 'dGPhd', 'zvWbW', 'pi82R', 'eAfrD', 'uZQ7V', 'GY3RN', '8mjL1', 'qGkVx', 'WCx5Z', '8T4GG', 'fXyg5', 'qY2DK', 'o7LoJ', 'DRqvb', 'ftHiZ', 'ZhnMj', 'PWDPZ', 'yfxio', 'CECMF', 'Z60kQ', 'uvLzv', 'Sbp92', 'FAJxR', 'Bx7mF', 'UjCHg', 'FTRmz', 'dfyJw', 'bcmMy', 'b14eW', 'ZGD74', 'iewSm'],
    ['1wwGD', 'Gvkhc', 'LDplC', 'XrNZ7', 'GKINj', 'FAJxR', 'fFJEm', 'Awq5q', 'bcmMy', 'PWDPZ', 'xgXl7', 'YIgvr', 'que8g', '8T4GG', 'GY3RN', 'Sbp92', 'dGPhd', '3SOuu', 'eAfrD', 'iewSm', 'ZhnMj', 'YrwUg', 'dfyJw', 'kTDfx', 'PLu7Z', 'DRqvb', 'nMdF0', '13btZ', '7Rhe9', 'yfxio', 'HKAJy', 'qY2DK', 'dOprv', 'uvLzv', 'KH7vd', 'yTbM9', 'rjdd0', 'CTnjV', 'ZDVCd', 'p7qpy', 'GqvJI', 'SKKMb', 'ON3rg', 'o7LoJ', '97tWK', 'qGkVx', 's0wsh', 'TxRwT', 'CECMF', 'zvWbW', 'xwo7N', 'WCx5Z', 'sMlfG', 'pi82R', 'Bx7mF', 'b14eW', 'UjCHg', 'ftHiZ', 'fXyg5', 'JvKbv', 'dk60w', 'FTRmz', 'uZQ7V', 'nK8xj', 'gwDDb', 'Z60kQ', 'Dzwnf', '8mjL1', 'ZGD74', 'DOAnc'],
    ['iewSm', 'CTnjV', 'fXyg5', 'Sbp92', 'kTDfx', 'dfyJw', 'YIgvr', 'PWDPZ', 'ZhnMj', 'HKAJy', 'o7LoJ', 'qY2DK', 'qGkVx', 'fFJEm', 'KH7vd', 'yfxio', 'sMlfG', 'uZQ7V', 'UjCHg', 'p7qpy', 'ZGD74', 'FTRmz', 'pi82R', 'SKKMb', 'rjdd0', 'Z60kQ', 'xgXl7', 'GY3RN', 'FAJxR', 'ON3rg', 'dOprv', 'Bx7mF', 'nMdF0', 'bcmMy', 'ftHiZ', 'eAfrD', 'DRqvb', 'dk60w', '97tWK', '3SOuu', 'TxRwT', '8mjL1', 'PLu7Z', 'LDplC', 'dGPhd', 'CECMF', '7Rhe9', 'uvLzv', 'xwo7N', 'XrNZ7', 'GqvJI', 'Gvkhc', 'YrwUg', 'WCx5Z', 'DOAnc', 's0wsh', 'Dzwnf', 'gwDDb', '13btZ', 'que8g', 'Awq5q', 'GKINj', '1wwGD', 'yTbM9', 'ZDVCd', 'nK8xj', 'b14eW', '8T4GG', 'JvKbv', 'zvWbW'],
    ['dk60w', 'ZGD74', 'GY3RN', 'CTnjV', '1wwGD', 'bcmMy', 'YrwUg', 'kTDfx', '8T4GG', 'DRqvb', 'b14eW', 'ON3rg', '97tWK', 'PLu7Z', 'zvWbW', 'Sbp92', 'ftHiZ', 'yfxio', 'GKINj', 'LDplC', 'Bx7mF', 'Gvkhc', 'FAJxR', 'sMlfG', 'xwo7N', 'fFJEm', 'o7LoJ', 'nMdF0', 'dfyJw', 'rjdd0', 'qGkVx', 'DOAnc', '8mjL1', 'WCx5Z', 'UjCHg', 'gwDDb', 'FTRmz', 'yTbM9', 'SKKMb', 's0wsh', '13btZ', 'GqvJI', 'uZQ7V', 'eAfrD', 'PWDPZ', 'HKAJy', 'CECMF', 'p7qpy', 'ZhnMj', 'iewSm', 'XrNZ7', 'KH7vd', 'dGPhd', 'Z60kQ', 'Awq5q', 'qY2DK', 'nK8xj', 'pi82R', 'fXyg5', 'xgXl7', 'ZDVCd', 'uvLzv', '3SOuu', 'Dzwnf', 'TxRwT', 'YIgvr', '7Rhe9', 'dOprv', 'que8g', 'JvKbv'],
    ['s0wsh', 'zvWbW', 'Z60kQ', 'Gvkhc', 'yfxio', 'qY2DK', 'UjCHg', 'GqvJI', 'LDplC', 'DRqvb', 'qGkVx', 'Bx7mF', 'Sbp92', 'Dzwnf', '3SOuu', 'PWDPZ', 'DOAnc', 'YIgvr', 'eAfrD', 'xwo7N', 'JvKbv', 'dOprv', 'rjdd0', '7Rhe9', 'uZQ7V', 'PLu7Z', 'uvLzv', 'CTnjV', 'ON3rg', 'GY3RN', 'KH7vd', 'ZGD74', 'fXyg5', 'TxRwT', 'nMdF0', 'dfyJw', 'XrNZ7', '8mjL1', 'HKAJy', 'ftHiZ', 'CECMF', '13btZ', 'nK8xj', 'kTDfx', 'SKKMb', 'xgXl7', 'p7qpy', 'gwDDb', 'fFJEm', 'FAJxR', 'YrwUg', '1wwGD', 'ZDVCd', 'FTRmz', 'o7LoJ', 'ZhnMj', 'GKINj', 'dk60w', '97tWK', 'yTbM9', 'Awq5q', 'dGPhd', '8T4GG', 'bcmMy', 'b14eW', 'que8g', 'WCx5Z', 'iewSm', 'pi82R', 'sMlfG'],
    ['ON3rg', 'dOprv', 'pi82R', 'o7LoJ', 'gwDDb', '1wwGD', 'JvKbv', 'GqvJI', 'bcmMy', 'uvLzv', 'YIgvr', 'b14eW', 'DRqvb', 'KH7vd', 'YrwUg', 'Bx7mF', '13btZ', 'FAJxR', 'yTbM9', '8T4GG', 'Dzwnf', 'p7qpy', 'xgXl7', 'WCx5Z', 'qGkVx', 'zvWbW', 'ZhnMj', 'SKKMb', 'sMlfG', 'dGPhd', 'GY3RN', 'ftHiZ', 'uZQ7V', 'Z60kQ', '8mjL1', 'dfyJw', 'que8g', 'nK8xj', 'PWDPZ', 'CECMF', 'kTDfx', 'dk60w', 'LDplC', 'HKAJy', '97tWK', 'ZGD74', 'eAfrD', 'nMdF0', 'qY2DK', 'Sbp92', 'fFJEm', 's0wsh', '7Rhe9', 'ZDVCd', 'rjdd0', 'TxRwT', 'CTnjV', 'Gvkhc', 'UjCHg', 'FTRmz', '3SOuu', 'DOAnc', 'fXyg5', 'GKINj', 'XrNZ7', 'PLu7Z', 'iewSm', 'yfxio', 'Awq5q', 'xwo7N'],
    ['que8g', 'Awq5q', 'HKAJy', 'uZQ7V', 'fXyg5', 'qGkVx', 'FTRmz', '1wwGD', 'UjCHg', 'dfyJw', 'zvWbW', 'gwDDb', 'ZDVCd', 'ZGD74', 'fFJEm', 'SKKMb', 'TxRwT', 'b14eW', 'DRqvb', 'CTnjV', 'CECMF', 'ON3rg', 'ftHiZ', '3SOuu', 'Bx7mF', 'KH7vd', 'rjdd0', 'xgXl7', 'o7LoJ', 'nMdF0', 'iewSm', 'GKINj', 'PWDPZ', '8mjL1', 'Dzwnf', 'dk60w', 'Sbp92', 's0wsh', 'PLu7Z', 'YrwUg', 'yfxio', 'qY2DK', '7Rhe9', '8T4GG', 'eAfrD', '97tWK', 'Z60kQ', 'pi82R', 'GqvJI', 'LDplC', 'DOAnc', 'bcmMy', 'xwo7N', 'nK8xj', 'FAJxR', 'WCx5Z', 'JvKbv', 'yTbM9', 'uvLzv', 'dGPhd', 'XrNZ7', 'Gvkhc', 'sMlfG', 'p7qpy', 'kTDfx', 'GY3RN', 'dOprv', 'YIgvr', 'ZhnMj', '13btZ'],
    ['yfxio', 'SKKMb', 'GqvJI', 'yTbM9', 'sMlfG', 'xgXl7', 'XrNZ7', 'ZGD74', 'dGPhd', 'gwDDb', 'nMdF0', 'ZhnMj', '7Rhe9', 'DRqvb', '13btZ', 'KH7vd', 'Bx7mF', '8T4GG', 'FAJxR', 'FTRmz', 'YrwUg', 'qY2DK', 'bcmMy', 'uZQ7V', 'o7LoJ', 'fXyg5', 'GKINj', 'LDplC', 'PWDPZ', '3SOuu', 'Gvkhc', '1wwGD', 's0wsh', 'ftHiZ', 'dfyJw', 'rjdd0', '97tWK', 'kTDfx', 'ZDVCd', 'eAfrD', 'GY3RN', 'uvLzv', 'fFJEm', 'CTnjV', 'HKAJy', 'dk60w', 'ON3rg', 'PLu7Z', 'dOprv', 'iewSm', 'JvKbv', 'p7qpy', 'que8g', 'pi82R', 'YIgvr', '8mjL1', 'DOAnc', 'xwo7N', 'b14eW', 'Sbp92', 'CECMF', 'TxRwT', 'UjCHg', 'Z60kQ', 'nK8xj', 'Awq5q', 'Dzwnf', 'WCx5Z', 'qGkVx', 'zvWbW'],
    ['ftHiZ', 'o7LoJ', 'dk60w', 'zvWbW', 'gwDDb', 'uvLzv', 's0wsh', 'ZDVCd', '8T4GG', 'nMdF0', '7Rhe9', 'KH7vd', 'YrwUg', 'xgXl7', 'HKAJy', 'TxRwT', 'Sbp92', 'dGPhd', 'fXyg5', 'ON3rg', 'sMlfG', 'UjCHg', '97tWK', 'FAJxR', 'bcmMy', 'DRqvb', 'Awq5q', 'qGkVx', 'FTRmz', 'kTDfx', 'que8g', 'eAfrD', 'b14eW', 'PWDPZ', 'Bx7mF', '13btZ', 'p7qpy', 'Z60kQ', '1wwGD', 'ZhnMj', 'uZQ7V', 'dfyJw', 'yTbM9', 'GqvJI', 'CTnjV', 'iewSm', 'pi82R', 'PLu7Z', 'nK8xj', 'fFJEm', 'Dzwnf', '8mjL1', 'Gvkhc', 'GKINj', 'xwo7N', 'DOAnc', 'rjdd0', 'yfxio', 'LDplC', 'GY3RN', 'YIgvr', 'CECMF', 'dOprv', 'ZGD74', 'SKKMb', 'qY2DK', 'XrNZ7', '3SOuu', 'JvKbv', 'WCx5Z'],
    ['kTDfx', 'YrwUg', 'FAJxR', 'KH7vd', 'CECMF', 'GKINj', 'ZDVCd', 'Dzwnf', 'ZGD74', 'sMlfG', 'dfyJw', 'dk60w', 'PLu7Z', '7Rhe9', 'ftHiZ', 'nK8xj', 'UjCHg', '8T4GG', 'FTRmz', 'Bx7mF', 'bcmMy', 'LDplC', 'xwo7N', 'nMdF0', '3SOuu', 'iewSm', 'yTbM9', 'SKKMb', 'yfxio', '13btZ', 'uZQ7V', 'dGPhd', 'Awq5q', 'pi82R', 'qY2DK', 'JvKbv', 'CTnjV', 'ON3rg', '8mjL1', 'fXyg5', 'b14eW', 'Gvkhc', 'gwDDb', 'qGkVx', 'rjdd0', 'fFJEm', 'TxRwT', 'o7LoJ', 'PWDPZ', 'xgXl7', 'ZhnMj', 's0wsh', 'GY3RN', 'YIgvr', 'que8g', 'XrNZ7', 'eAfrD', 'uvLzv', 'Sbp92', 'WCx5Z', 'dOprv', 'p7qpy', 'Z60kQ', '1wwGD', '97tWK', 'DOAnc', 'GqvJI', 'DRqvb', 'zvWbW', 'HKAJy'],
    ['DOAnc', 'GqvJI', 'qY2DK', '7Rhe9', 'p7qpy', 'fFJEm', '8mjL1', 'TxRwT', 'HKAJy', 'dfyJw', 'bcmMy', 'FTRmz', 'FAJxR', 'Awq5q', 'xwo7N', 'Dzwnf', 'ZhnMj', 'UjCHg', 'b14eW', 'PWDPZ', 'yTbM9', 'Bx7mF', 'pi82R', 'YrwUg', 'XrNZ7', 'JvKbv', 'CTnjV', 'dOprv', 'dGPhd', 'KH7vd', 'Gvkhc', 'sMlfG', 'ZGD74', 'rjdd0', 'gwDDb', 'xgXl7', 'LDplC', '1wwGD', 'GKINj', 'PLu7Z', 'que8g', 'uZQ7V', 'kTDfx', 'zvWbW', 'WCx5Z', 'CECMF', 'ON3rg', 'nK8xj', '8T4GG', 'dk60w', '97tWK', 'SKKMb', 'YIgvr', 'GY3RN', 'ftHiZ', 'DRqvb', 'iewSm', 'o7LoJ', 'Sbp92', 'eAfrD', 'nMdF0', 'qGkVx', 's0wsh', 'uvLzv', '13btZ', 'Z60kQ', 'fXyg5', 'yfxio', 'ZDVCd', '3SOuu'],
    ['Dzwnf', 'o7LoJ', 'ZhnMj', 's0wsh', '1wwGD', 'TxRwT', 'GKINj', 'dGPhd', 'Gvkhc', 'CECMF', 'que8g', 'CTnjV', 'qGkVx', 'KH7vd', 'PLu7Z', 'nK8xj', 'FAJxR', 'uZQ7V', 'ZDVCd', 'bcmMy', 'iewSm', 'UjCHg', 'ZGD74', 'yfxio', '8mjL1', 'p7qpy', 'XrNZ7', 'Bx7mF', 'xgXl7', 'gwDDb', 'dfyJw', 'dk60w', 'YIgvr', 'dOprv', 'kTDfx', '8T4GG', 'fFJEm', 'xwo7N', 'GY3RN', 'pi82R', 'JvKbv', '13btZ', 'zvWbW', 'eAfrD', 'DOAnc', 'DRqvb', 'yTbM9', 'b14eW', 'Sbp92', 'HKAJy', 'PWDPZ', 'Z60kQ', 'YrwUg', 'fXyg5', 'LDplC', '97tWK', 'qY2DK', 'ON3rg', 'uvLzv', 'Awq5q', 'rjdd0', 'WCx5Z', '7Rhe9', 'GqvJI', 'SKKMb', '3SOuu', 'sMlfG', 'nMdF0', 'FTRmz', 'ftHiZ'],
    ['PWDPZ', 'b14eW', 'qGkVx', 'HKAJy', 'xgXl7', 'GKINj', 'yfxio', 'qY2DK', 'fXyg5', 'fFJEm', 'KH7vd', 'YIgvr', 'dfyJw', 'CTnjV', 'rjdd0', 'nK8xj', '1wwGD', 'GqvJI', 'Dzwnf', 'Bx7mF', '3SOuu', 'CECMF', 'nMdF0', 'JvKbv', 'Z60kQ', 'SKKMb', 'GY3RN', 'que8g', 'ZDVCd', 'o7LoJ', 'TxRwT', '7Rhe9', 'ftHiZ', 'DOAnc', 'FAJxR', 'bcmMy', 'sMlfG', 'Awq5q', 'UjCHg', 'gwDDb', 'dOprv', 'WCx5Z', 'XrNZ7', 'kTDfx', 'YrwUg', '97tWK', 'ZGD74', 'DRqvb', 'uvLzv', 'PLu7Z', 'iewSm', 's0wsh', 'uZQ7V', 'xwo7N', 'pi82R', 'eAfrD', '8T4GG', 'Sbp92', 'Gvkhc', 'yTbM9', 'dGPhd', 'LDplC', 'FTRmz', 'ON3rg', 'dk60w', 'ZhnMj', '13btZ', 'p7qpy', '8mjL1', 'zvWbW'],
    ['HKAJy', '97tWK', 'qY2DK', '1wwGD', 'uvLzv', 'Bx7mF', 'PLu7Z', 'Awq5q', 'dOprv', 'SKKMb', 'fXyg5', 'bcmMy', '7Rhe9', 'yfxio', 'dfyJw', 'Z60kQ', '3SOuu', 'gwDDb', 'CTnjV', 'GKINj', 'LDplC', 'TxRwT', 'YrwUg', 'DRqvb', 'JvKbv', 'dk60w', 'nK8xj', 'WCx5Z', 'fFJEm', 'YIgvr', 'GqvJI', 'kTDfx', 'p7qpy', '8mjL1', 'zvWbW', 'uZQ7V', 'KH7vd', 'GY3RN', 'ZGD74', 'iewSm', 'xwo7N', 'ON3rg', 'b14eW', 'qGkVx', 'CECMF', 'Dzwnf', 'XrNZ7', 'Gvkhc', 'DOAnc', 'dGPhd', 'ftHiZ', 'ZDVCd', 'xgXl7', 'o7LoJ', 'Sbp92', 'yTbM9', 'PWDPZ', 'nMdF0', 'que8g', 'FTRmz', '13btZ', 'rjdd0', 'sMlfG', 'eAfrD', 'FAJxR', 'pi82R', 'UjCHg', 'ZhnMj', '8T4GG', 's0wsh'],
    ['gwDDb', 'GY3RN', 'DRqvb', 'ZhnMj', 'qGkVx', 'yTbM9', 's0wsh', 'bcmMy', '7Rhe9', 'zvWbW', 'dk60w', 'WCx5Z', '97tWK', 'ZDVCd', 'pi82R', 'KH7vd', 'GKINj', 'PLu7Z', 'xgXl7', 'b14eW', 'dGPhd', 'yfxio', 'HKAJy', 'SKKMb', 'XrNZ7', '8T4GG', 'PWDPZ', 'Bx7mF', 'dfyJw', 'ftHiZ', '8mjL1', 'CTnjV', '1wwGD', 'TxRwT', 'FAJxR', 'nMdF0', 'Z60kQ', 'ON3rg', 'JvKbv', 'Sbp92', 'sMlfG', 'fXyg5', 'CECMF', 'iewSm', 'dOprv', 'ZGD74', 'YIgvr', 'GqvJI', 'qY2DK', 'uZQ7V', 'LDplC', 'kTDfx', 'rjdd0', 'que8g', 'Dzwnf', 'fFJEm', '3SOuu', 'eAfrD', 'p7qpy', 'FTRmz', 'nK8xj', 'YrwUg', 'Awq5q', 'UjCHg', '13btZ', 'Gvkhc', 'uvLzv', 'xwo7N', 'DOAnc', 'o7LoJ'],
    ['PLu7Z', '8mjL1', 'bcmMy', 'JvKbv', 'FAJxR', 'nK8xj', 's0wsh', 'yfxio', 'DRqvb', 'eAfrD', '3SOuu', 'ZGD74', 'dk60w', '97tWK', 'TxRwT', 'ftHiZ', 'GY3RN', 'fXyg5', 'ON3rg', '1wwGD', 'Sbp92', 'pi82R', 'sMlfG', 'xwo7N', 'Bx7mF', 'qGkVx', 'CECMF', 'PWDPZ', 'zvWbW', 'dGPhd', 'HKAJy', 'YrwUg', 'Dzwnf', 'Awq5q', 'ZDVCd', 'p7qpy', 'yTbM9', 'LDplC', 'qY2DK', 'FTRmz', 'YIgvr', 'uvLzv', 'KH7vd', 'que8g', 'xgXl7', 'GqvJI', '7Rhe9', 'kTDfx', 'rjdd0', '8T4GG', 'UjCHg', 'dOprv', 'b14eW', 'XrNZ7', 'uZQ7V', 'GKINj', '13btZ', 'Gvkhc', 'ZhnMj', 'DOAnc', 'SKKMb', 'CTnjV', 'iewSm', 'nMdF0', 'fFJEm', 'Z60kQ', 'gwDDb', 'dfyJw', 'o7LoJ', 'WCx5Z'],
    ['yTbM9', 'dk60w', 'fFJEm', 'SKKMb', 'CTnjV', 'KH7vd', 'b14eW', 'DRqvb', 'xwo7N', 'FAJxR', 'ftHiZ', 'Dzwnf', 'FTRmz', 'bcmMy', 'dOprv', 'ZhnMj', 'nMdF0', 'XrNZ7', 'YIgvr', 'zvWbW', 'eAfrD', 'GY3RN', 's0wsh', 'GqvJI', '1wwGD', 'ZGD74', 'fXyg5', 'qGkVx', 'p7qpy', 'LDplC', 'que8g', 'uvLzv', '13btZ', 'DOAnc', 'dGPhd', 'iewSm', 'yfxio', 'PWDPZ', 'WCx5Z', 'UjCHg', 'Z60kQ', '3SOuu', 'uZQ7V', 'xgXl7', 'PLu7Z', 'dfyJw', '8mjL1', 'ZDVCd', '7Rhe9', '97tWK', 'Gvkhc', 'Bx7mF', '8T4GG', 'qY2DK', 'GKINj', 'nK8xj', 'TxRwT', 'JvKbv', 'o7LoJ', 'pi82R', 'CECMF', 'HKAJy', 'kTDfx', 'gwDDb', 'rjdd0', 'sMlfG', 'YrwUg', 'Awq5q', 'Sbp92', 'ON3rg'],
    ['iewSm', 'PWDPZ', '8mjL1', 'Z60kQ', 'ON3rg', 'dGPhd', 'KH7vd', 'DRqvb', 'sMlfG', 'que8g', 'PLu7Z', 'ZhnMj', 'dfyJw', 'WCx5Z', 'YIgvr', 'HKAJy', 'kTDfx', '13btZ', 'CTnjV', 'Sbp92', 'Gvkhc', 'fFJEm', 'zvWbW', 'SKKMb', 'gwDDb', 'yTbM9', 'JvKbv', '8T4GG', 'XrNZ7', 'bcmMy', 'GY3RN', 'b14eW', 'TxRwT', 'DOAnc', 'ZDVCd', 'YrwUg', 'nMdF0', 'p7qpy', 'FAJxR', 'qGkVx', 'Awq5q', 'pi82R', 'eAfrD', 'xgXl7', '97tWK', 'nK8xj', 'LDplC', 'qY2DK', 'uZQ7V', 'fXyg5', '7Rhe9', 'uvLzv', 'UjCHg', 'rjdd0', '1wwGD', '3SOuu', 'CECMF', 'ftHiZ', 'yfxio', 'dk60w', 'o7LoJ', 'Bx7mF', 'ZGD74', 'GKINj', 'FTRmz', 'Dzwnf', 'xwo7N', 'GqvJI', 'dOprv', 's0wsh'],
    ['dfyJw', 'Awq5q', 'o7LoJ', 'HKAJy', 'ZhnMj', 'dk60w', 'fXyg5', 'Gvkhc', 'sMlfG', 'yTbM9', 'XrNZ7', 'ZDVCd', '7Rhe9', 'uZQ7V', 'fFJEm', 'GKINj', 'kTDfx', '3SOuu', 'qY2DK', 'que8g', '97tWK', 'FAJxR', 'b14eW', 'uvLzv', 'DOAnc', 'xgXl7', 'SKKMb', 'YIgvr', 'qGkVx', 'GY3RN', 'ON3rg', 'ZGD74', 'PLu7Z', 'ftHiZ', 'JvKbv', 'Sbp92', '1wwGD', 'dOprv', 'eAfrD', '8mjL1', 'yfxio', 'Z60kQ', 'UjCHg', 'dGPhd', 's0wsh', 'DRqvb', 'KH7vd', 'xwo7N', 'CTnjV', 'YrwUg', 'Bx7mF', 'bcmMy', 'nMdF0', 'p7qpy', '8T4GG', 'TxRwT', 'pi82R', 'LDplC', 'CECMF', 'WCx5Z', 'gwDDb', 'GqvJI', 'FTRmz', 'iewSm', 'rjdd0', 'Dzwnf', 'nK8xj', '13btZ', 'zvWbW', 'PWDPZ'],
    ['Z60kQ', 'FTRmz', 'o7LoJ', 'que8g', 'xwo7N', 's0wsh', 'WCx5Z', 'yTbM9', 'TxRwT', 'DRqvb', 'fFJEm', 'dfyJw', 'CECMF', 'yfxio', 'fXyg5', 'pi82R', 'PLu7Z', '1wwGD', '13btZ', 'zvWbW', 'dGPhd', 'GY3RN', 'ZGD74', 'uvLzv', 'ftHiZ', 'YIgvr', 'dOprv', 'uZQ7V', 'qGkVx', 'JvKbv', 'nK8xj', 'DOAnc', 'rjdd0', 'KH7vd', 'LDplC', 'bcmMy', 'Dzwnf', 'xgXl7', 'CTnjV', 'XrNZ7', 'iewSm', 'Awq5q', 'kTDfx', 'Bx7mF', 'GqvJI', 'gwDDb', '7Rhe9', 'qY2DK', 'YrwUg', 'FAJxR', 'ON3rg', 'PWDPZ', 'nMdF0', 'eAfrD', '3SOuu', '97tWK', '8mjL1', 'UjCHg', 'HKAJy', 'dk60w', 'Gvkhc', 'Sbp92', 'ZDVCd', 'b14eW', 'SKKMb', '8T4GG', 'ZhnMj', 'sMlfG', 'p7qpy', 'GKINj'],
    ['ZGD74', 'SKKMb', 'rjdd0', 'HKAJy', 'UjCHg', 'kTDfx', 'FTRmz', 'dk60w', 'qY2DK', 'dGPhd', '97tWK', 'nMdF0', 'CTnjV', '8mjL1', 'PWDPZ', 'qGkVx', 'YrwUg', 's0wsh', 'WCx5Z', 'o7LoJ', 'nK8xj', 'FAJxR', 'Sbp92', 'DOAnc', 'uvLzv', 'JvKbv', 'fXyg5', 'Dzwnf', 'YIgvr', 'TxRwT', 'b14eW', '1wwGD', 'p7qpy', 'zvWbW', 'ON3rg', 'eAfrD', 'ftHiZ', '13btZ', 'iewSm', 'Z60kQ', '7Rhe9', '3SOuu', 'ZDVCd', 'dfyJw', 'LDplC', 'yfxio', 'Awq5q', 'XrNZ7', 'pi82R', '8T4GG', 'yTbM9', 'GqvJI', 'CECMF', 'fFJEm', 'Bx7mF', 'Gvkhc', 'PLu7Z', 'GKINj', 'bcmMy', 'GY3RN', 'dOprv', 'DRqvb', 'xgXl7', 'que8g', 'xwo7N', 'ZhnMj', 'uZQ7V', 'KH7vd', 'sMlfG', 'gwDDb'],
    ['o7LoJ', 'dGPhd', 'dfyJw', 'uvLzv', 'fXyg5', 'ZhnMj', 'Gvkhc', 'Dzwnf', 'ftHiZ', 'nK8xj', 'eAfrD', 'Sbp92', 'Z60kQ', 'GqvJI', '97tWK', 'ZGD74', 'GKINj', 'FTRmz', '13btZ', 'kTDfx', 'JvKbv', 'nMdF0', 'fFJEm', 'b14eW', 'Awq5q', 'CECMF', 'sMlfG', 's0wsh', 'GY3RN', 'qY2DK', 'que8g', 'YIgvr', 'KH7vd', 'yfxio', 'zvWbW', 'YrwUg', 'DRqvb', 'qGkVx', 'yTbM9', 'Bx7mF', 'SKKMb', 'FAJxR', 'LDplC', 'rjdd0', 'uZQ7V', 'UjCHg', 'ZDVCd', '8T4GG', '3SOuu', 'xwo7N', 'TxRwT', 'ON3rg', 'iewSm', 'gwDDb', 'dk60w', 'XrNZ7', 'PLu7Z', '8mjL1', 'pi82R', 'xgXl7', 'HKAJy', '1wwGD', '7Rhe9', 'dOprv', 'CTnjV', 'PWDPZ', 'p7qpy', 'bcmMy', 'DOAnc', 'WCx5Z'],
    ['fFJEm', 'zvWbW', 'iewSm', 'uZQ7V', 'GqvJI', 'Gvkhc', 'CECMF', '1wwGD', 'dk60w', 'dfyJw', 'ZDVCd', 'YrwUg', 's0wsh', 'HKAJy', 'KH7vd', 'b14eW', 'DOAnc', 'ZGD74', 'rjdd0', 'nMdF0', 'ftHiZ', 'yfxio', 'nK8xj', 'dGPhd', 'CTnjV', 'Bx7mF', 'TxRwT', 'JvKbv', 'XrNZ7', '8T4GG', 'PWDPZ', 'bcmMy', 'UjCHg', 'SKKMb', 'qGkVx', '13btZ', 'qY2DK', 'PLu7Z', 'Awq5q', 'fXyg5', 'LDplC', '7Rhe9', 'que8g', 'pi82R', 'uvLzv', 'ZhnMj', 'DRqvb', 'Z60kQ', 'xwo7N', 'GY3RN', '8mjL1', 'p7qpy', 'WCx5Z', 'Sbp92', 'kTDfx', 'GKINj', 'YIgvr', '97tWK', 'sMlfG', 'FTRmz', 'Dzwnf', 'o7LoJ', 'yTbM9', 'ON3rg', 'eAfrD', '3SOuu', 'FAJxR', 'xgXl7', 'dOprv', 'gwDDb'],
    ['ZhnMj', 'pi82R', '8T4GG', 'ftHiZ', 'ZGD74', 'eAfrD', 'JvKbv', 'Awq5q', 'dGPhd', 'yfxio', 'p7qpy', 'dk60w', 'ON3rg', 'PWDPZ', 'b14eW', 'o7LoJ', 'DOAnc', 'fFJEm', 'LDplC', 'KH7vd', '13btZ', 'GqvJI', 'rjdd0', 'PLu7Z', '97tWK', 'xgXl7', 'UjCHg', 'zvWbW', 'TxRwT', 'GY3RN', 'WCx5Z', 'qY2DK', 'GKINj', 'nMdF0', 'sMlfG', 'CECMF', 'que8g', 'Bx7mF', 'FTRmz', 'dOprv', 'yTbM9', 'CTnjV', 'fXyg5', 'dfyJw', 'qGkVx', 'YrwUg', 'iewSm', 'uZQ7V', 'SKKMb', 's0wsh', 'HKAJy', 'FAJxR', 'Dzwnf', 'uvLzv', 'kTDfx', 'YIgvr', '3SOuu', 'Sbp92', '1wwGD', 'DRqvb', 'Gvkhc', 'gwDDb', 'nK8xj', 'bcmMy', 'xwo7N', 'XrNZ7', '8mjL1', 'Z60kQ', '7Rhe9', 'ZDVCd'],
    ['o7LoJ', 'YrwUg', 'FAJxR', 'dGPhd', 'Sbp92', 'que8g', 'Awq5q', 'TxRwT', 'ftHiZ', '7Rhe9', 'uvLzv', '3SOuu', 'XrNZ7', 'DRqvb', 'YIgvr', 'bcmMy', 'pi82R', 'uZQ7V', 'gwDDb', 'yTbM9', 'PWDPZ', 'Z60kQ', 'fXyg5', 'Gvkhc', 'p7qpy', 'nK8xj', 'PLu7Z', '1wwGD', 'HKAJy', 'kTDfx', 'GqvJI', 'ZDVCd', 'CTnjV', '13btZ', 'b14eW', 'CECMF', 'WCx5Z', 'UjCHg', 'ON3rg', 'xwo7N', 'iewSm', 'ZGD74', 'dfyJw', 's0wsh', 'qGkVx', 'nMdF0', 'fFJEm', 'Bx7mF', 'KH7vd', 'sMlfG', 'ZhnMj', 'JvKbv', 'rjdd0', '97tWK', '8mjL1', 'yfxio', 'SKKMb', 'dk60w', 'zvWbW', 'xgXl7', 'eAfrD', 'FTRmz', 'LDplC', '8T4GG', 'DOAnc', 'GKINj', 'qY2DK', 'dOprv', 'GY3RN', 'Dzwnf'],
    ['zvWbW', 'dOprv', 'KH7vd', 'ZGD74', 'xgXl7', '3SOuu', '8mjL1', 'qGkVx', 'UjCHg', 'dk60w', 'yfxio', 'Sbp92', 'eAfrD', 'xwo7N', 'fXyg5', 'HKAJy', 'iewSm', 'ftHiZ', '7Rhe9', 'pi82R', 'GqvJI', 'gwDDb', 'sMlfG', 'CTnjV', 'Awq5q', 'dfyJw', 'ON3rg', 'FTRmz', 'Dzwnf', 'XrNZ7', 'PLu7Z', 'uvLzv', 'kTDfx', 'ZDVCd', '13btZ', 'FAJxR', '97tWK', '8T4GG', 'JvKbv', 'PWDPZ', 'Z60kQ', 'DOAnc', 'nMdF0', 'Bx7mF', 'b14eW', 'rjdd0', 'SKKMb', 'bcmMy', 'p7qpy', 'WCx5Z', 'DRqvb', 'TxRwT', '1wwGD', 'GY3RN', 'GKINj', 'CECMF', 'o7LoJ', 'YrwUg', 'nK8xj', 'uZQ7V', 'fFJEm', 'ZhnMj', 'qY2DK', 'dGPhd', 'LDplC', 'Gvkhc', 'YIgvr', 's0wsh', 'yTbM9', 'que8g'],
    ['Sbp92', '8mjL1', 'WCx5Z', '97tWK', 'rjdd0', 'xgXl7', 'PWDPZ', 'eAfrD', 'ZGD74', 'b14eW', 'bcmMy', 'fFJEm', 'o7LoJ', '13btZ', 'CTnjV', 'KH7vd', '7Rhe9', 'nMdF0', 'uvLzv', 'ZDVCd', 'uZQ7V', 'LDplC', 'nK8xj', 'yfxio', 'kTDfx', 'JvKbv', 'Dzwnf', 'PLu7Z', 'gwDDb', 'sMlfG', 'ON3rg', 'p7qpy', '1wwGD', 'que8g', 'DOAnc', 'YrwUg', 'YIgvr', 'ftHiZ', 'CECMF', 'UjCHg', 'DRqvb', 'dGPhd', 'TxRwT', 'GqvJI', 'Bx7mF', 'GKINj', 'GY3RN', 'FTRmz', 'zvWbW', 'ZhnMj', 'XrNZ7', 'fXyg5', 'dk60w', 'yTbM9', 's0wsh', 'pi82R', 'SKKMb', 'xwo7N', 'HKAJy', 'dfyJw', 'iewSm', 'dOprv', 'FAJxR', '8T4GG', 'qY2DK', 'qGkVx', '3SOuu', 'Z60kQ', 'Awq5q', 'Gvkhc'],
    ['PLu7Z', 'dfyJw', 'Bx7mF', 'dOprv', 'LDplC', '1wwGD', 'iewSm', '13btZ', 'ZhnMj', 'ON3rg', '7Rhe9', 'GKINj', 'yTbM9', 'nMdF0', 'ZDVCd', 'uvLzv', 'zvWbW', 'KH7vd', 'kTDfx', 'o7LoJ', 'ZGD74', 'qGkVx', '8mjL1', 'YrwUg', 'Dzwnf', 's0wsh', 'Gvkhc', 'p7qpy', 'GY3RN', 'fFJEm', 'b14eW', 'pi82R', 'PWDPZ', 'UjCHg', 'HKAJy', 'dGPhd', 'XrNZ7', 'qY2DK', 'eAfrD', 'GqvJI', 'CECMF', 'FAJxR', 'DOAnc', 'xgXl7', 'WCx5Z', 'JvKbv', '8T4GG', 'yfxio', 'Sbp92', 'SKKMb', 'CTnjV', 'ftHiZ', 'bcmMy', '3SOuu', 'gwDDb', 'Z60kQ', 'dk60w', 'sMlfG', 'DRqvb', 'rjdd0', 'que8g', '97tWK', 'Awq5q', 'FTRmz', 'fXyg5', 'YIgvr', 'uZQ7V', 'TxRwT', 'nK8xj', 'xwo7N'],
    ['rjdd0', 'ZDVCd', 'qGkVx', 'ZGD74', 'PLu7Z', 'p7qpy', 'FAJxR', 'ftHiZ', 'qY2DK', 'Bx7mF', 'yTbM9', 'sMlfG', 'TxRwT', 'eAfrD', 'gwDDb', 'Dzwnf', 'LDplC', 'nMdF0', 'que8g', 'uvLzv', 'GqvJI', 'dOprv', 'YIgvr', 'WCx5Z', 'dk60w', 'zvWbW', 'o7LoJ', 'Gvkhc', 'Z60kQ', '1wwGD', '8T4GG', 's0wsh', 'PWDPZ', 'UjCHg', 'b14eW', 'uZQ7V', '7Rhe9', 'CECMF', 'bcmMy', 'DOAnc', 'HKAJy', 'FTRmz', 'CTnjV', 'fXyg5', 'yfxio', 'fFJEm', 'kTDfx', 'YrwUg', 'XrNZ7', 'iewSm', 'xgXl7', 'dGPhd', 'pi82R', 'nK8xj', 'KH7vd', '13btZ', 'GY3RN', '3SOuu', 'SKKMb', 'Awq5q', 'DRqvb', 'JvKbv', 'ZhnMj', 'GKINj', '97tWK', 'xwo7N', 'Sbp92', 'dfyJw', '8mjL1', 'ON3rg'],
    ['ZGD74', 'YIgvr', 'Bx7mF', 'CECMF', 'ftHiZ', 'GKINj', 'b14eW', 'dOprv', 'eAfrD', 'bcmMy', '8mjL1', 'GqvJI', 'qY2DK', 'LDplC', 'WCx5Z', '7Rhe9', 'SKKMb', 'p7qpy', 'DRqvb', 'PLu7Z', 'zvWbW', 'DOAnc', 'fFJEm', 'Z60kQ', 'yfxio', 'GY3RN', 'uvLzv', 'CTnjV', 'XrNZ7', 'rjdd0', 'gwDDb', 'FTRmz', 'ON3rg', 'Gvkhc', '97tWK', 'Dzwnf', '13btZ', 'dGPhd', 'ZhnMj', 'iewSm', 'TxRwT', 'yTbM9', 'ZDVCd', 'HKAJy', 'YrwUg', 'pi82R', 'uZQ7V', 'xgXl7', 'nMdF0', 'UjCHg', '3SOuu', 'nK8xj', 'que8g', 'o7LoJ', 'dk60w', 'FAJxR', 'sMlfG', 'xwo7N', 'Sbp92', 'qGkVx', '1wwGD', 'PWDPZ', 'Awq5q', 'kTDfx', '8T4GG', 'dfyJw', 'fXyg5', 'KH7vd', 'JvKbv', 's0wsh'],
    ['iewSm', 'CTnjV', 'dk60w', 'Gvkhc', 'ON3rg', 'GY3RN', 'Bx7mF', 'Dzwnf', 'WCx5Z', 'sMlfG', 'YrwUg', 'b14eW', 'dfyJw', 'kTDfx', '1wwGD', 'PWDPZ', 'DOAnc', 'qY2DK', 'XrNZ7', 'xgXl7', 'Awq5q', '13btZ', '8mjL1', 'Sbp92', 'fFJEm', 'nK8xj', 'nMdF0', 'eAfrD', 'qGkVx', 'GKINj', 'CECMF', 'p7qpy', '7Rhe9', 'pi82R', 'ZDVCd', '97tWK', 'ZGD74', 'uZQ7V', 'GqvJI', 'FAJxR', 'xwo7N', 'ZhnMj', 'HKAJy', 'ftHiZ', 'rjdd0', 'fXyg5', 'dGPhd', '8T4GG', 'dOprv', 'Z60kQ', 'uvLzv', 'gwDDb', 'yfxio', 'KH7vd', '3SOuu', 'DRqvb', 'yTbM9', 'PLu7Z', 's0wsh', 'JvKbv', 'YIgvr', 'zvWbW', 'o7LoJ', 'que8g', 'LDplC', 'TxRwT', 'bcmMy', 'FTRmz', 'SKKMb', 'UjCHg'],
    ['WCx5Z', 'ftHiZ', 'ZhnMj', 'bcmMy', 'TxRwT', 'PWDPZ', 'Bx7mF', 'JvKbv', 'iewSm', 'KH7vd', 's0wsh', 'Awq5q', 'GY3RN', 'o7LoJ', 'dOprv', 'PLu7Z', 'que8g', 'CECMF', '3SOuu', '97tWK', 'uvLzv', 'rjdd0', 'fXyg5', 'qGkVx', 'CTnjV', 'xwo7N', 'p7qpy', 'nK8xj', '8T4GG', 'gwDDb', 'yTbM9', 'SKKMb', 'xgXl7', 'DRqvb', 'dk60w', 'zvWbW', 'eAfrD', 'FAJxR', 'b14eW', 'qY2DK', 'Gvkhc', 'dfyJw', 'pi82R', 'GqvJI', 'Z60kQ', 'uZQ7V', 'DOAnc', 'ZGD74', 'nMdF0', 'dGPhd', 'ZDVCd', 'sMlfG', 'XrNZ7', 'YIgvr', 'FTRmz', '1wwGD', 'LDplC', 'fFJEm', '13btZ', '7Rhe9', 'ON3rg', 'Dzwnf', 'Sbp92', 'yfxio', 'YrwUg', 'kTDfx', '8mjL1', 'UjCHg', 'HKAJy', 'GKINj'],
    ['dk60w', 'ftHiZ', 'XrNZ7', 'TxRwT', 'pi82R', 'nMdF0', 'gwDDb', 'ON3rg', 'kTDfx', 'fXyg5', 'LDplC', 'Z60kQ', 'WCx5Z', 'nK8xj', 'bcmMy', 'Gvkhc', 'xwo7N', 'dOprv', 'ZDVCd', 'o7LoJ', 'iewSm', 'DRqvb', 'uZQ7V', 'yTbM9', 'FAJxR', 'GqvJI', 'ZhnMj', 'Bx7mF', 'b14eW', 'dGPhd', 's0wsh', 'CTnjV', 'PWDPZ', '13btZ', 'yfxio', 'HKAJy', 'fFJEm', 'KH7vd', 'rjdd0', 'DOAnc', 'YrwUg', 'Dzwnf', 'JvKbv', 'GY3RN', 'que8g', 'CECMF', '8mjL1', 'Awq5q', 'xgXl7', 'eAfrD', 'ZGD74', 'UjCHg', 'qGkVx', 'dfyJw', '3SOuu', '1wwGD', '7Rhe9', 'uvLzv', 'Sbp92', 'FTRmz', 'GKINj', '8T4GG', 'YIgvr', 'zvWbW', 'PLu7Z', 'sMlfG', 'p7qpy', '97tWK', 'qY2DK', 'SKKMb'],
    ['FAJxR', 'bcmMy', 'pi82R', 'iewSm', 'Awq5q', 'o7LoJ', 'KH7vd', '1wwGD', 'dGPhd', 'rjdd0', 'yfxio', 'fFJEm', 'sMlfG', 'WCx5Z', 'PLu7Z', 'dfyJw', 'ZDVCd', 'DRqvb', '8T4GG', 'Bx7mF', 'PWDPZ', 'que8g', 'YrwUg', 'p7qpy', 'qY2DK', 'Sbp92', 'YIgvr', 'nK8xj', 'XrNZ7', 'ZhnMj', 'ftHiZ', 'UjCHg', 'HKAJy', 'uvLzv', 'GqvJI', 'eAfrD', '7Rhe9', 'zvWbW', 'FTRmz', 'DOAnc', 'JvKbv', 's0wsh', 'LDplC', '13btZ', '3SOuu', 'qGkVx', 'xgXl7', 'GY3RN', 'gwDDb', 'GKINj', 'ON3rg', 'uZQ7V', '8mjL1', '97tWK', 'dOprv', 'SKKMb', 'Z60kQ', 'yTbM9', 'ZGD74', 'fXyg5', 'kTDfx', 'xwo7N', 'TxRwT', 'CECMF', 'b14eW', 'dk60w', 'Gvkhc', 'nMdF0', 'Dzwnf', 'CTnjV'],
    ['XrNZ7', 'qY2DK', 'p7qpy', '1wwGD', '3SOuu', 'DRqvb', 'LDplC', '8mjL1', 'SKKMb', 'nMdF0', 'ftHiZ', 'nK8xj', 'Dzwnf', 'b14eW', 'ZGD74', 'dk60w', 'JvKbv', 'CECMF', 'GY3RN', 'yTbM9', 'pi82R', 'xwo7N', 'rjdd0', 'fFJEm', 'YIgvr', 'YrwUg', 'ZhnMj', 'FTRmz', 'Bx7mF', 'kTDfx', 'dfyJw', 'Gvkhc', 'sMlfG', 'GqvJI', 'dGPhd', 'UjCHg', 'TxRwT', 'fXyg5', 'KH7vd', 'xgXl7', 'eAfrD', 'uvLzv', 'PWDPZ', '13btZ', 'Sbp92', '97tWK', 'HKAJy', '7Rhe9', 's0wsh', '8T4GG', 'o7LoJ', 'bcmMy', 'Z60kQ', 'dOprv', 'ON3rg', 'yfxio', 'GKINj', 'uZQ7V', 'WCx5Z', 'CTnjV', 'que8g', 'DOAnc', 'Awq5q', 'PLu7Z', 'zvWbW', 'gwDDb', 'iewSm', 'ZDVCd', 'qGkVx', 'FAJxR'],
    ['bcmMy', '7Rhe9', 'xgXl7', '8mjL1', 'GY3RN', 'WCx5Z', 'fXyg5', 'nK8xj', 'dOprv', 'Dzwnf', 'Sbp92', 'qGkVx', 'dk60w', 'ZGD74', 'eAfrD', 'FTRmz', 'gwDDb', 'KH7vd', 'Bx7mF', 'xwo7N', 'uvLzv', 'CTnjV', 'SKKMb', 'yTbM9', 'JvKbv', '3SOuu', 'pi82R', 'LDplC', 'sMlfG', 'kTDfx', 'YrwUg', 'DOAnc', '97tWK', 'dGPhd', 'GqvJI', 'nMdF0', 'FAJxR', 'ON3rg', 's0wsh', 'ftHiZ', '8T4GG', 'YIgvr', 'Awq5q', 'b14eW', 'ZhnMj', 'XrNZ7', 'qY2DK', '13btZ', 'fFJEm', 'dfyJw', 'Gvkhc', 'PWDPZ', 'que8g', 'rjdd0', 'yfxio', 'iewSm', 'CECMF', 'uZQ7V', 'Z60kQ', 'UjCHg', 'zvWbW', 'o7LoJ', '1wwGD', 'TxRwT', 'ZDVCd', 'DRqvb', 'p7qpy', 'GKINj', 'PLu7Z', 'HKAJy'],
    ['DOAnc', 'YrwUg', 'uZQ7V', 'JvKbv', 'FTRmz', 'Z60kQ', 'FAJxR', '1wwGD', 'que8g', 'qY2DK', '8T4GG', 'pi82R', 'TxRwT', 'dGPhd', 'Gvkhc', 'LDplC', 'sMlfG', 'GKINj', 'zvWbW', 'ftHiZ', 'XrNZ7', 'dfyJw', 'fFJEm', '13btZ', 'kTDfx', 'ZGD74', 'yTbM9', 'CECMF', 'dOprv', 'KH7vd', 'PWDPZ', 'ZhnMj', 'iewSm', 'Dzwnf', 's0wsh', 'bcmMy', 'ZDVCd', 'qGkVx', 'CTnjV', 'uvLzv', 'PLu7Z', '3SOuu', 'DRqvb', 'b14eW', 'ON3rg', 'eAfrD', '8mjL1', 'xwo7N', 'p7qpy', '97tWK', 'HKAJy', 'gwDDb', 'Bx7mF', 'dk60w', 'GqvJI', 'rjdd0', 'WCx5Z', 'yfxio', 'fXyg5', 'nK8xj', 'xgXl7', 'Sbp92', 'SKKMb', 'nMdF0', '7Rhe9', 'Awq5q', 'YIgvr', 'UjCHg', 'GY3RN', 'o7LoJ'],
    ['pi82R', 'DOAnc', 'ZGD74', 'GKINj', 'uvLzv', 'UjCHg', 'xwo7N', 'PLu7Z', '97tWK', 'KH7vd', 'TxRwT', 'CTnjV', 'Z60kQ', 'GY3RN', '13btZ', 'ZDVCd', 'bcmMy', 'dfyJw', '3SOuu', 'que8g', 'ZhnMj', 'ON3rg', '1wwGD', 'LDplC', 'Bx7mF', 'FTRmz', 'SKKMb', 'Dzwnf', 'YrwUg', 'PWDPZ', 'xgXl7', 'qGkVx', '7Rhe9', 'JvKbv', 'eAfrD', 'gwDDb', 'rjdd0', 'nMdF0', 'DRqvb', 'GqvJI', 'CECMF', 'YIgvr', 'iewSm', 'Sbp92', '8T4GG', 'dOprv', 'o7LoJ', 'sMlfG', 'qY2DK', 'HKAJy', 'dk60w', 'fXyg5', 'uZQ7V', 'zvWbW', 'nK8xj', 'ftHiZ', 'Awq5q', 'kTDfx', 'yTbM9', 'Gvkhc', 'dGPhd', 'FAJxR', 'p7qpy', 'WCx5Z', 'fFJEm', 'yfxio', 'XrNZ7', 'b14eW', '8mjL1', 's0wsh'],


]
 #Fim matriz

def criptografia(chave,mensagem): #Função responsavel por pegar o texto e criptografar
    if len(mensagem) <= 128:    #verifica o tamanho da mensagem para limitar!!
        texto_pronto = ''
        valorh = 0  #essa variavel é para ajudar no laço de repetição
        for h in range(len(mensagem)): #repetir o numero do tamanho da mensagem
            h = valorh # serve para nao bugar o primeiro for
            for i in range(len(chave)): #repetir no numero do tamanho da chave
                for j in range(len(dicionario_pt)): #repetir o tamaho do dicionario
                    if chave[i]==dicionario_pt[j]: #verifica qual indice do dicionario é =  a letra da chave
                        seleçaoalfa1 = j    #Aki vai ser salvo o primeiro indice da matriz (o alfabeto que sera usado)
                        break #para o laço J
                for k in range(len(dicionario_pt)): #repete o tamanho do dicionario
                    if (h != len(mensagem)):    #verifica se h tem o mesmo tamanho de mensagem, se tiver ele nao executara (out of range)
                        if mensagem[h] == dicionario_pt[k]: # verifica o equivalente da mensagem h com o dicionario de k
                            texto_pronto = texto_pronto + matriz[seleçaoalfa1][k]+ " " # Variavel responsavel por concatenar os valores dos resultados
                            h = h+1 #precisei fazer isso pra nao bugar o laço
                            """toda vez que ele saia do laço com h valendo 4 e voltava la em cima, o h voltava no 2 """
                            valorh = h
                            break
            if valorh == len(mensagem): #verificação para parar as repetiçoes 
                break
        return texto_pronto #vai retornar o valor da criptografia
    else:  # esse else é do primeiro if, se a mensagem for > 128 caracteres ele executa essa ação!
        print("="*50)
        print("o valor da mensagem excede o limite de 128 caracteres")
        print("="*50)

def descriptografia(chave,mensagem): #Função responsavel por pegar o codigo criptografado e descriptografar
    texto_pronto = ''
    valorh = 0
    for h in range(len(mensagem)): #repetir o numero do tamanho da mensagem
        h = valorh
        itens = mensagem.split(" ") #itens vai receber a mensagem criptografada e alocar ela como uma lista, separando ela pelos " "
        if len(itens) > 128:    #verifica o tamanho da lista itens para limitar!
            print("="*50)
            print("o valor da mensagem excede o limite de 128 caracteres")
            print("="*50)
            break   #Para o laço e volta para o menu
        for i in range(len(chave)): #repetir no numero do tamanho da chave
            for j in range(len(dicionario_pt)): #repetir o tamaho do dicionario
                if chave[i]==dicionario_pt[j]: #verifica qual indice do dicionario é =  a letra da chave
                    seleçaoalfa1 = j #aki é definido o alfabeto que sera usado (Dicionario_"letra")
                    break   #Para o laço J e vai para o laço K
            for k in range(len(dicionario_pt)): #percorre o dicionario todo
                if (h != len(itens)): 
                    """se o h for igual ao tamanho de itens ele nao executa pq o h é o tamanho da mensagem 
                    e o responsavel por definir a letra da chave""" 
                    if itens[h] == matriz[seleçaoalfa1][k]: #verifica se o valor armazenado em item[h] é igual ao da matriz
                        texto_pronto = texto_pronto + dicionario_pt[k] #concatena o texto novo
                        h = h+1 
                        valorh = h
                        break
        if valorh == len(mensagem):#termino do primeiro laço
            break
    return texto_pronto

def info():
    print("="*50)
    print("Seja Bem vindo ao cripto:")
    print("O objetivo do programa é criptografar e descriptografar mensagens de ate 128 caracteres!")
    print("O funcionamento consiste em: receber uma chave e uma mensagem \nO comprimento da chave deve ser menor ou igual ao comprimento da mensagem!")
    print("O programa reconhece o alfabeto de (A a Z) diferenciando maiuscula e minuscula\nNumeros de (0 a 9) e os caracteres especiais 'ç'-'Ç'-'!'-','-'?'-':' e '.'")
    print("Quando for pedido uma opção voce devera digitar uma dentre as 4 opções mostradas!")
    print("="*50)
    menu()


def menu():
    opção = ""
    while opção != "4": #Repetição para que o menu fique sempre sendo executado, exceto quando a opção for 3(Sair)
        print("="*50)
        print("(1) Instruções \n(2) Criptografar \n(3) Descriptografar \n(4) Sair")
        print("="*50)
        opção = (input("Digite a opção desejada: "))
        print("="*50)
        if opção == "1" or opção == "2" or opção == "3": # se a opção for diferente de 3 ele entra nesse if
            if opção == "1":
                print(info())
            chave = input("digite a chave: ")
            print("="*50) 
            if len(chave) > 128:    #Verifica o tamanho da chave para limitala ate 128 caracteres
                print("="*50)
                print("o valor da chave excede o limite de 128 caracteres")
                print("="*50)
                chave = ""
                menu()
            mensagem = input("digite a mensagem: ")
            print("="*50)
            if len(chave) <= len(mensagem): 
                """Verifica se achave é maior que a mensagem para poder executar
                (chave = chave mensagem = ola) só vai ser usado "cha" de "chave" ou seja
                parte da chave ficaria inutilizada!"""
                if opção == "2":
                    print(criptografia(chave,mensagem))
                elif opção == "3":
                    print(descriptografia(chave,mensagem))
            else:# esse else é da verificaçao do tamanho da chave com a mensagem!
                print("="*50)
                print("A Chave deve ser Menor ou igual a mensagem!")
                print("="*50)
        elif opção == "4":
            print(">> FIM <<")
            sys.exit(0) #Tive que importar sys pra usar esse comando que sai do programa assim que executado!
        
        elif opção != "1" and "2" and "3" and "4":
            print("="*50)
            print('O valor "{}" não pode ser aceito!'.format(opção))
            print("Apenas 1, 2, 3 e 4 são valores validos.")
            print("="*50)
info()

